name: another_audio_recorder
description: (Null-Safe + V2) Audio Record Plugin that supports record, pause, resume, stop, and provide access to audio level metering properties average power peak power.
version: 1.0.0+1
homepage: https://github.com/loonix/another_audio_recorder

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  path: ^1.8.0
  flutter:
    sdk: flutter
  file: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.loonix.another_audio_recorder
        pluginClass: AnotherAudioRecorderPlugin
      ios:
        pluginClass: AnotherAudioRecorderPlugin